### ISSUE TITLE
Support for tags other than script

### ISSUE THREAD

**Issue by mmajchrzak** [Cognifide/knotx#107]
Currently, when a developer creates a dynamic snippet it must be surrounded by:
`<script data-api-type="templating" [...]>[...]</script>`. While in most cases this is super fine, there are cases where this limitation may be problematic. For instance, the repository interprets `script` tags on its own or changes its behaviour upon `script` tags (real cases: AEM Link Transformer does not working; HTL conflicts).
Knot.x should not rely on tag names but rather on their attributes - it should be enough to check if data-api-type="templating" on any element exists, and if so then interprets such an element as snippet root.

**Comment by marcinczeczko** [comment]
Relying on just tag attributes to discover Knot.x snippet is kind of cumbersome due to the way how Knot.x process HTML itself.
However, what if we introduced custom HTML tag, for instance <snippet> or <knotx-snippet> - anything that's not in HTML spec.
The question is if those mechanism you're referring are capable of parsing such tags ? especially to modify theirs attributes (by mentioned link transformer) ?

Answer on this would give help us to decide in what direction we should go.
