### ISSUE TITLE
Replace CountDownLatch with CompositeFuture

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#17]
We can replace CountDownLatch with Vert.x async responses coordination: http://vertx.io/docs/apidocs/io/vertx/core/CompositeFuture.html.

**Comment by marcinczeczko** [comment]
Actually, this countdown latch (as well as composite future) suppose to be removed in favour of Observable features. I think you're referring to Template rendering implementation. If so, we have Observable created over keySet of snippets. Observable emits three kinds of events: on next,  on error and on complete. In our implementation we use only first two. If you add lambda expression as third parameter to subscribe method then this lambda will be executed when observable finish emitting events - in our case when last element from keySet will be emitted.
So instead of costing snippets simply add lambda that will finish processing all snippets.
```
.subsribe (item -> {},
                   error -> {},
                   () -> {/* on complete */}
               );
```

For a reference: http://reactivex.io/documentation/operators/subscribe.html

**Comment by marcinczeczko** [comment]
We can close this issue after merging rxified version of knota
