### ISSUE TITLE
Including header 'Edge-Control' and lowercasing request & response headers

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/knotx#325]
Take a look at:

![image](https://user-images.githubusercontent.com/10673561/29410817-a00f0fd2-8352-11e7-9f82-23d47094d2a2.png)

Knot.X Server and/or HttpRepository is unecessararily lowercasing all proxied request & response headers like 'Edge-Control'. I know that all headers are case insensitive, but generally speaking it just looks bad (we know that knot.x is running under the hood :D)

I am also recommending to add 'Edge-Control' to default allowedResponseHeaders.

What is more is we want to pass such header we need to add it to both config's for these two items in 'allowedResponseHeaders' which is confusing.

**Comment by jwadolowski** [comment]
`Surrogate-Control` is also quite popular caching response header and it'd be great to have it present on default header whitelist.

**Comment by marcinczeczko** [comment]
Actually, keeping the headers in a camel case is kind of challanging - it's not possible at the moment. It's because how the underlying vert.x and netty handles the headers. If the headers were case sensitve it would be a very intensive operation. Anyway RFC says that header names are case insensitive.
Having this in ming, I'm closing the ticket as it's not possible to make it happen.

Besides allowing extra headers as you and @jwadolowski requestes - it's done on #347 - already in master.
