### ISSUE TITLE
EventBus timeout is not configurable, current timout is 30s

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#343]
We are not able to change the default event bus timeout. It means that all modules have to do their job within 30s - if not the timeout exception is thrown from Knot.x.

**Comment by Skejven** [comment]
30 s is the default timeout setting on the [`Event Bus`](http://vertx.io/docs/vertx-core/java/#event_bus).
The change of this value is possible via ['DeploymentOptions`](http://vertx.io/docs/apidocs/io/vertx/core/DeploymentOptions.html).
In the case of some Knot.x modules, we use a Service Proxy to setup communication between Verticles.
Changing this timeout there would be more complicated, because it is not possible with the version of Vert.x we are using (3.4.X).
Fix for that was introduced in Vert.x 3.5.0: https://github.com/eclipse/vert.x/pull/2072
Thanks to it, we can extend Knot.x proxies with `DeploymentOptions` parameter which can be passed directly from config files.
But first we need to upgrade to Vert.x 3.5 :)

**Comment by marcinczeczko** [comment]
well in my opinion, if module not responds within 30 seconds it means something is badly designed. it does not make sense to have anything responding in so long time

**Comment by tomaszmichalak** [comment]
@marcinczeczko you are right that modules / vertices should not do their work in more than 30 seconds. However, cases where this time is not predictable - for example, the response from the HTML repository - can be very fast for clients, but for others really slow (think about authoring part).

So changing this timeout is not good idea but we should not block it.

**Comment by marcinczeczko** [comment]
I disagree. 30 seconds for authoring is also really bad. If authoring getting in 30s then publish will not be much faster

**Comment by Skejven** [comment]
Fixed in #349 .
